<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PRODUCTOS</name>
   <tag></tag>
   <elementGuidId>30a868ab-9799-4bff-a2b8-56abff5122fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div[3]/ul[2]/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>654a99ac-91be-4b7d-81e3-52f62bf76100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#productos</value>
      <webElementGuid>6f5dc1f7-f772-4949-9c61-84352fc16ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRODUCTOS</value>
      <webElementGuid>8c5f3abf-29a2-42d4-9daf-ce9c3eb258fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-inner&quot;]/div[@class=&quot;nav-menu singlepage-nav&quot;]/ul[@class=&quot;nav-menu-inner&quot;]/li[3]/a[1]</value>
      <webElementGuid>fe87b353-1d58-45d7-bebf-1dc3abff1ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div[3]/ul[2]/li[3]/a</value>
      <webElementGuid>b703a1e4-629e-4bdf-915d-d8ab041b17b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PRODUCTOS')]</value>
      <webElementGuid>1440c92b-4f38-426d-a3fe-28507efc4798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPAÑÍA'])[1]/following::a[1]</value>
      <webElementGuid>3a7eec33-b0f7-426c-91d3-732055943dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[2]</value>
      <webElementGuid>3e2e2eb2-fd25-4781-8ac0-55ace09d2510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LANZAMIENTOS'])[1]/preceding::a[1]</value>
      <webElementGuid>afc4f4b9-1ecd-4e70-836b-0d4aba95d754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FARMACOVIGILANCIA'])[1]/preceding::a[2]</value>
      <webElementGuid>043d7cfd-7b9c-4038-ac20-86bbc133073f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PRODUCTOS']/parent::*</value>
      <webElementGuid>bbfea37a-238d-4039-be53-1025a95d5eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#productos')]</value>
      <webElementGuid>e90d0e60-e02f-478f-b62b-60cbe9ea7eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>c1fa4f59-2f3e-499c-9fbb-a96fa4df99ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#productos' and (text() = 'PRODUCTOS' or . = 'PRODUCTOS')]</value>
      <webElementGuid>22cbaa19-c5d9-4c42-bf02-ac7cb665d65e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
